'use strict';

/**
 * Copilot adapter — writes to .github/copilot-instructions.md
 * GitHub Copilot reads this file automatically in every workspace.
 *
 * Contract:
 *   format(context, opts?) → string
 *   outputPath(cwd) → string
 */

const path = require('path');

const name = 'copilot';

/**
 * Format context for GitHub Copilot instructions.
 * @param {string} context - Raw signature context string
 * @param {object} [opts]
 * @param {string} [opts.version] - SigMap version string
 * @returns {string}
 */
function format(context, opts = {}) {
  if (!context || typeof context !== 'string') return '';
  const version = opts.version || 'unknown';
  const timestamp = new Date().toISOString();
  const header = [
    `<!-- Generated by SigMap gen-context.js v${version} -->`,
    `<!-- Updated: ${timestamp} -->`,
    `<!-- Do not edit below — regenerate with: node gen-context.js -->`,
    '',
    '# Code signatures',
    '',
  ].join('\n');
  return header + context;
}

/**
 * Return the output file path for this adapter.
 * @param {string} cwd - Project root
 * @returns {string}
 */
function outputPath(cwd) {
  return path.join(cwd, '.github', 'copilot-instructions.md');
}

module.exports = { name, format, outputPath };
